server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      import: optional:configserver:http://localhost:8888:name:config-server # 구성정보 설정
      server:
        native:
          search-locations: file:///D:/Spring_lecture/ecommerce-msa
#        git:
#          local git사용
#          uri: file:///D:/Spring_lecture/ecommerce-msa
#          remote git 사용
#          uri: https://github.com/레포url
#          username: [username]
#          password: [password]


management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

